name       : fuse-emulator
version    : 1.3.0
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/fuse-emulator/fuse/1.3.0/fuse-1.3.0.tar.gz : 7aa1d6e057a09ffe661494514115d271f73a79e032bafc7a6fd78db4adce06ad
license    : GPL-2.0
component  : games.emulator
summary    : Free Unix Spectrum Emulator (ZX Spectrum)
description: |
    Free Unix Spectrum Emulator (ZX Spectrum)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpng)
    - pkgconfig(pango)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - libspectrum-devel
setup      : |
    %configure --enable-desktop-integration
build      : |
    %make
install    : |
    %make_install
