name       : fuse-emulator
version    : 1.5.7
release    : 5
source     :
    - https://sourceforge.net/projects/fuse-emulator/files/fuse/1.5.7/fuse-1.5.7.tar.gz/download : f0e2583f2642cdc3b2a737910d24e289d46e4f7e151805e3b0827024b2b45e4d
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Free Unix Spectrum Emulator (ZX Spectrum)
description: |
    Free Unix Spectrum Emulator (ZX Spectrum)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpng)
    - pkgconfig(pango)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - libspectrum-devel
setup      : |
    %configure --enable-desktop-integration
build      : |
    %make
install    : |
    %make_install
