name       : fuse-emulator
version    : 1.3.5
release    : 3
source     :
    - https://iweb.dl.sourceforge.net/project/fuse-emulator/fuse/1.3.5/fuse-1.3.5.tar.gz : f7829c4331220f09acdc1185ed40db1bfe15d0dbd6a3c08e4e6b3cc3f8a699cd
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Free Unix Spectrum Emulator (ZX Spectrum)
description: |
    Free Unix Spectrum Emulator (ZX Spectrum)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpng)
    - pkgconfig(pango)
    - pkgconfig(sdl)
    - pkgconfig(x11)
    - libspectrum-devel
setup      : |
    %configure --enable-desktop-integration
build      : |
    %make
install    : |
    %make_install
